jupyter/docker-demo-images

Dockerfile

Not sure if this is right place to get R packages onto the tmpnb.org notebooks... In any case, it would be really handy to have the `dplyr` package in there. Thanks.

install the dplyr R package

---

common/ipython_notebook_config.py

This lets us embed the demo image in an iframe under:
* https://*.jupyter.org
* https://jupyter.github.io
* https://*.tmpnb.org

Include Content Security Policy

---

Dockerfile

vim for use in the terminal when on tmpnb.

Install vim in the large demo image

---

Dockerfile

Hopefully this fixes the need for the c++11 patch. I haven't got the chance to see if it works in your setup, so it's worth checking before accepting.

Removed need for c++11 patch

---

Dockerfile

This adds the Strata content with @jdfreder directly on build.

Directly add the Strata tutorial content

---

README.md

@rgbkrk is this along the lines of what you were thinking about?  Should I add similar verbage to the Welcome ipynb?

added a Community Notebooks section to readme

---

Dockerfile

I hope this is right! I cargo culted from what was in the Dockerfile already.

Add pandas cookbook to featured notebooks

---

Dockerfile

Runs nbconvert on all the notebooks to upgrade them to v4 (and beyond).
/cc @jdfreder

Convert included notebooks to the current format

---

Dockerfile
notebooks/Welcome R  - demo.ipynb

This combines many of the package installation lines together, since Docker won't allow images to have > 127 parent images. Additionally, I swapped the logo out to pull from Wikipedia since it wasn't local to the notebook it was referenced in.

Combinr - combine R lines in the Dockerfile

---

common/Dockerfile

Bring in custom js to expose for nginx

---

Dockerfile
common/Dockerfile

A separate PR for shrinking `jupyter/demo` and `jupyter/minimal`.
As requested by @rgbkrk  https://github.com/jupyter/docker-demo-images/pull/29#issuecomment-99899375

Further shrink jupyter/minimal and jupyter/demo

---

common/templates/page.html

* Bring the little logo in over HTTPS so we get that nice green lock of approval
* Open the link in a separate pane so it doesn't look like the user is still on https://try.jupyter.org

Cleanup icon experience

---

Dockerfile

Add IHaskell to `jupyter/demo`.

Add IHaskell

---

Dockerfile

The `build.sh` script did this automatically before.

Install the IHaskell kernelspec

---

Dockerfile

Remove the ihaskell binary

---

Dockerfile

Reverts jupyter/docker-demo-images#43
@rgbkrk It seems like I misinterpreted the situation. Sorry for bothering you.

Revert "Remove the ihaskell binary"

---

Dockerfile

IRuby 0.2.0 works with jupyter. Would be great if you add it :)

add iruby kernel

---

notebooks/Welcome to Haskell.ipynb

Includes an intro to the Jupyter interface, a few Haskell code snippets, and links to other materials.

Adding a "Welcome to Haskell" demo notebook

---

Dockerfile

This sets up a Python 2 kernel. It also sneaks in dill (for Pythons) and nyaplot (for the Ruby kernel).
/cc @minad

Setup Python2 kernel, nyaplot for Ruby, dill 4 py

---

Dockerfile

Simplify use of f2py (they would have had to figure out the direct path).

Put f2py on the path, install gfortran.

---

datasets/thebutton/README.md

Comes straight from https://github.com/reddit/thebutton-data.
Related blog post: http://www.redditblog.com/2015/06/the-button-has-ended.html

Bring in /r/thebutton data

---

Makefile

This just makes it easy to do the build+upload in one fell swoop.
`make upload`

Upload option for Makefile

---

Dockerfile

Based on https://github.com/SciRuby/sciruby-notebooks/blob/master/Dockerfile. This install all the interesting libraries from the sciruby-project, including nyaplot etc.

use sciruby-full

---

Dockerfile

Bring in more packages from R. Like it says on the tin.

Bring in more R packages

---

Dockerfile
Makefile
common/profile_default/static/custom/custom.js

Added missing dependencies, initial `IPython` availability in custom.js, super nuke of current docker images (for full rebuild from scratch).

Image updates

---

notebooks/communities/pyladies/Python 101.ipynb

Hello! try.jupyter rocks! Here's a pull for a PyLadies community directory with one introductory notebook. I didn't make a `pyladies` branch since I didn't see other branches yet... but I could do this...
Thanks!

adding a PyLadies community with a 101 intro to python notebook

---

Dockerfile

I would like to use try.jupyter.org for a workshop on web scraping which uses Beautiful Soup.

Add beautiful-soup to to python modules in python3

---

README.md

Addresses comments in #65 and #27.

Add FAQ to README

---

Dockerfile

Updating `ihaskell-widgets` to the latest release.

Updating ihaskell-widgets to 0.2.2.1

---

Dockerfile

update notebook base tag

---

Dockerfile

**waiting on test build to confirm that it works**
0.2.10 fixes version conflict that caused us to remove it
closes #88

restore sciruby-0.2.10

---

Dockerfile

Please don't lock the sciruby gem version

---

notebooks/Welcome to Ruby.ipynb

A simple tutorial adapted from [Ruby in twenty minutes](https://www.ruby-lang.org/en/documentation/quickstart/)

Welcome to Ruby notebook

---

Dockerfile
notebooks/Welcome to Perl 6.ipynb

Hello!
Would you consider this PR to add the Perl 6 kernel and sample notebook to the tmpnb service?
Thanks for offering the service, and thanks in advance for considering this for inclusion.
all the best
Brian

Add Perl 6 kernel and sample notebook
